apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mongodb-ss.yaml
- mongodb-svc.yaml
- ./network-policies/allow-color-api.yaml


configMapGenerator:
- files:
  - mongo-init.js
  name: mongodb-init-colordb

# labels:
# - includeSelectors: true
#   pairs:
#     app: mongodb
#     project: proj-gke
